services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'   # Public HTTP
      - '443:443' # Public HTTPS
      - '81:81'   # Admin Web Interface
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  nginx-depot:
    image: nginx:alpine
    volumes:
      - ./nginx-depot.conf:/etc/nginx/nginx.conf:ro
      - /mnt/storage/depot:/data/depot:ro 
    restart: unless-stopped
