events {}

http {
  server {
    listen 80;

    # Disable Byte-Range requests
    max_ranges 0;
    set $http_range "";
    add_header Accept-Ranges "none" always;

    # Performance
    gzip off;

    location / {
      root /data/depot;
      autoindex on;
    }
  }
}
