services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    environment:
      - TZ=America/New_York
      - WEBPASSWORD=VMwar123!
      - FTLCONF_misc_etc_dnsmasq_d=true
    volumes:
      # 1. Stateful data moves to the local NVMe storage (outside Git)
      - /mnt/storage/apps/pihole/etc-pihole:/etc/pihole
      
      # 2. Shared info between nodes
      - /home/labadmin/homelab-ops/common/pihole:/etc/dnsmasq.d:ro
    dns:
      - 127.0.0.1
      - 1.1.1.1    

